# Generated by Django 4.1.7 on 2023-05-23 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Ответ')),
                ('creating_time', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('editing_time', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('is_editing', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Корректный ответ')),
            ],
            options={
                'verbose_name': ('Ответ',),
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Аватарка')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ник')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': ('Профиль',),
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('creating_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('editing_time', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('is_editing', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='app.profile', verbose_name='Автор')),
            ],
            options={
                'verbose_name': ('Вопрос',),
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-creating_time'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Тег')),
            ],
            options={
                'verbose_name': ('Тег',),
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.profile', verbose_name='Лайкнул')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='app.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': ('Лайк вопроса',),
                'verbose_name_plural': 'Лайки вопроса',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='app.tag', verbose_name='Тег'),
        ),
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='app.answer', verbose_name='Ответ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.profile', verbose_name='Лайкнул')),
            ],
            options={
                'verbose_name': ('Лайк ответа',),
                'verbose_name_plural': 'Лайки ответа',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.profile', verbose_name='Ответчик'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.question', verbose_name='Вопрос'),
        ),
    ]
