# Generated by Django 4.1.7 on 2023-05-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerlike',
            options={'verbose_name': ('Лайк ответа',), 'verbose_name_plural': 'Лайки ответов'},
        ),
        migrations.AlterModelOptions(
            name='questionlike',
            options={'verbose_name': ('Лайк вопроса',), 'verbose_name_plural': 'Лайки вопросов'},
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('answer', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('question', 'author')},
        ),
    ]
