# Generated by Django 4.1.7 on 2023-05-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_answerlike_options_alter_questionlike_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/base.jpg', null=True, upload_to='img', verbose_name='Аватарка'),
        ),
    ]
